---

- name: Ensure folder exists
  file:
    path: ~/ansible
    state: directory

- name: Copy script
  ansible.builtin.template:
    src: "ansible.vm.sh.j2"
    dest: "~/ansible/vm.{{ args_proxmox_id }}.sh"
    owner: root
    group: root
    mode: 0755

- name: Run script
  shell: ~/ansible/vm.{{ args_proxmox_id }}.sh
  args:
    executable: /bin/bash
