---

- name: If python not detected
  when: 'prop_proxmox_python_path is not defined'
  block:
    - name: Detect Python on os
      shell: |
        {% for path in prop_python_paths %}
          result=$( {{ role_path }}/scripts/test.python.sh "{{ prop_proxmox_host }}" "{{ prop_admin_username }}" "{{ path }}" )
          if [[ "$?" != "0" ]]; then 
            echo "Error executing script"
            exit
          fi
          if [[ "$result" != "" ]]; then
            echo $result
            exit
          fi
        {% endfor %}
      args:
        executable: /bin/bash
      register: expectresult
      changed_when: 'expectresult.stdout != ""'
      failed_when: '"Error" in expectresult.stdout'
      vars:
        ansible_python_interpreter: "{{ prop_local_python_path }}"
      connection: local
      become: false

    - name: set os python path
      ansible.builtin.set_fact:
        prop_proxmox_python_path: "{{ expectresult.stdout }}"
      failed_when: '("Error" in expectresult.stdout) or (expectresult.stdout == "")'

