---

- ansible.builtin.include_role:
    name: alex.proxmox.removevm

- name: Restore [{{ prop_proxmox_vmid }}]
  shell: |
    qmrestore /mnt/build-dev/vm-qemu-base/vzdump-qemu-{{ prop_proxmox_vmid }}-*.vma.zst {{ prop_proxmox_vmid }}
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  async: 3000
  poll: 15
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true

- ansible.builtin.include_role:
    name: alex.proxmox.setmeta

- ansible.builtin.include_role:
    name: alex.proxmox.sethardware
