---

- ansible.builtin.include_role: # knownproxmoxhost
    name: alex.base.knownoshost

- include_tasks: repositories.yml

- ansible.builtin.include_role: # configuser
    name: alex.preinstall.configuser

- ansible.builtin.include_role: # installsmbclient
    name: alex.linux.installsmbclient

- ansible.builtin.include_role: # mountsmbshare
    name: alex.linux.mountsmbshare

- ansible.builtin.include_role: # certificates
    name: alex.preinstall.certificates

- ansible.builtin.include_role: # aptupgrade
    name: alex.preinstall.aptupgrade

- ansible.builtin.include_role: # basecommands
    name: alex.preinstall.basecommands

- include_tasks: storage.yml

- ansible.builtin.include_role: # ms.server
    name: alex.ms.server

