---

- name: Get VM/Template status
  shell: |
    status=$(qm status {{ args_vmid }} 2> /dev/null )
    if [ $? -ne 0 ] ; then
      echo NOTEXIST
    else
      if [ $( echo $status | grep "running" | wc -l ) -eq 1 ] ; then
        echo RUNNING
      elif [ $( echo $status | grep "stopped" | wc -l ) -eq 1 ] ; then
        echo STOPPED
      else
        echo NOTIMPLEMENTED
      fi
      template=$(qm config {{ args_vmid }} 2> /dev/null | grep template | wc -l)
      if [ $template -eq 1 ] ; then
        echo TEMPLATE
      fi
    fi
  register: vmstatusresult
  changed_when: 'false'
  failed_when: '"NOTIMPLEMENTED" in vmstatusresult.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_proxmox_host }}"
  become: true
