---

- name: Check VM exists
  shell: 'qm status {{ args_proxmox_vmid }} >/dev/null 2>&1 ; echo $?'
  register: vmresult
  changed_when: 'false'

- name: start vm
  shell: 'qm start {{ args_proxmox_vmid }} >/dev/null 2>&1 ; echo $?'
  register: vmresult
  changed_when: 'true'
  when: '"0" in vmresult.stdout'
