---

- ansible.builtin.include_role:
    name: alex.proxmox.status
  vars:
    args_status_vmid: "{{ args_shutdown_vmid }}"
    args_status_host: "{{ args_shutdown_host }}"

- name: shutdown [{{ args_shutdown_vmid }}]
  shell: |
    qm shutdown {{ args_shutdown_vmid }} --skiplock --forceStop
    if [ "$?" -ne "0" ]; then
      echo "FAILED"
      exit 1
    fi
    qm wait {{ args_shutdown_vmid }}
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  when: '"RUNNING" in result_status.stdout'
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_shutdown_host }}"
  become: true
