---

- name: Remove specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
    state: absent

- name: Remove specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-pacific bullseye main
    state: absent

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
