---

- name: Set Tags [{{ prop_proxmox_vmid }}]
  shell: |
    tags="arch-{{ prop_arch }};os-{{ prop_os }};env-{{ prop_environment }};type-{{ prop_proxmox_type }}"
    qm set {{ prop_proxmox_vmid }} --tags $tags
  args:
    executable: /bin/bash
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true

- name: Set Notes [{{ prop_proxmox_vmid }}]
  shell: |
    qm set {{ prop_proxmox_vmid }} --name "{{ prop_proxmox_name }}" 
    description=$'# {{ prop_hostname }}  \n{{ prop_description }}  \n{{ prop_arch }}  \n{{ prop_os }}  \n{{ prop_ipaddress }}  \n{{ prop_environment }}  \n'
    description+="$(date)"
    description+=$'  \n'
    if [ "{{ prop_weburl | default('null') }}" != "null" ]; then
      description+=$'<a href="{{ prop_weburl | default("null") }}" target="_blank">web</a>  \n'
    fi
    qm set {{ prop_proxmox_vmid }} --description "$description"
  args:
    executable: /bin/bash
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true
