---

- ansible.builtin.include_role:
    name: alex.proxmox.status
  vars:
    args_status_vmid: "{{ args_stop_vmid }}"
    args_status_host: "{{ args_stop_host }}"

- name: Stop [{{ args_stop_vmid }}]
  shell: |
    qm stop {{ args_stop_vmid }} --skiplock
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  when: '"RUNNING" in result_status.stdout'
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_stop_host }}"
  become: true
