---

- name: Set networks [{{ prop_proxmox_vmid }}]
  shell: |
    interface=$( qm config {{ prop_proxmox_vmid }} | grep "^net" | cut -c 1-4 | grep {{ item.name }} )
    if [ ! -z "$interface" ]; then
      net=model=virtio,macaddr={{ item.mac }},bridge=vmbr0,firewall=1
      if [ "{{ item.vlan }}" -gt "0" ]; then
        net=$net,tag={{ item.vlan }}
      fi
      echo $net
      qm set {{ prop_proxmox_vmid }} --{{ item.name }} $net
      if [ "$?" -eq "0" ]; then
        echo "CHANGED"
      else
        echo "FAILED"
      fi
    fi
  args:
    executable: /bin/bash
  register: result
  loop: "{{ prop_vm_installnetwork }}"
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true
