---

- ansible.builtin.include_role:
    name: alex.proxmox.stopvm

- name: Remove [{{ prop_proxmox_vmid }}]
  shell: |
    qm destroy {{ prop_proxmox_vmid }} --skiplock --purge
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  when: '"NOTEXIST" not in result_status.stdout'
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true
