---

- name: remove vm
  shell: |
    qm destroy {{ args_vmid }} --skiplock --purge
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_proxmox_host }}"
  become: true
