---

- ansible.builtin.include_role:
    name: alex.proxmox.status
  vars:
    args_status_vmid: "{{ args_start_vmid }}"
    args_status_host: "{{ args_start_host }}"

- name: start vm [{{ args_start_vmid }}]
  shell: |
    qm start {{ args_start_vmid }}
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  when: '"RUNNING" not in result_status.stdout'
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_start_host }}"
  become: true
