---

- ansible.builtin.include_role:
    name: alex.proxmox.statusvm

- name: start vm [{{ prop_proxmox_vmid }}]
  shell: |
    qm start {{ prop_proxmox_vmid }}
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  when: '"RUNNING" not in result_status.stdout'
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
    ansible_python_interpreter: "{{ prop_proxmox_python_path }}"
  become: true
