---

- ansible.builtin.include_role:
    name: alex.proxmox.statusvm

- ansible.builtin.include_role:
    name: alex.proxmox.shutdownvm
  when: '"RUNNING" in result_status.stdout'

- name: Backup [{{ prop_proxmox_vmid }}]
  shell: |
    vzdump {{ prop_proxmox_vmid }} --mode stop --compress zstd --dumpdir /mnt/build-dev/vm-qemu-tmpl --prune-backups keep-last=1
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  args:
    executable: /bin/bash
  async: 3000
  poll: 15
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_proxmox_host }}"
  become: true
