---

- name: "Playbook: configure os"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # configureos
        name: alex.proxmox.configureos
