---

- name: "Playbook: Config Proxmox Host"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # configureproxmox
        name: alex.proxmox.configureproxmoxhost



