---

- name: "Playbook: Rebuild VM"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  roles:
    - name: alex.proxmox.status
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
    - name: alex.proxmox.stopvm
      when: '"RUNNING" in vmstatusresult.stdout'
    - name: alex.proxmox.removevm
      when: '"NOTEXIST" not in vmstatusresult.stdout'
    - name: alex.proxmox.status
      vars:
        args_vmid: "{{ prop_proxmox_template }}"
      failed_when: '"NOTEXIST" not in vmstatusresult.stdout'
    - name: alex.proxmox.addvm
      vars:
        args_template: "{{ prop_proxmox_template }}"
    - name: alex.proxmox.startvm
