---

- name: "Playbook: Create/recreate test server {{ args_proxmox_name }}"
  hosts: "{{ args_host }}"
  gather_facts: false
  become: true
  remote_user: root

  vars:
  - ansible_host: "{{ args_proxmox_host }}"

  roles:
  - alex.proxmox.vm
