---

- name: "Playbook: Remove [{{ args_host }}]"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.proxmox.remove
      vars:
        args_remove_vmid: "{{ prop_proxmox_vmid }}"
        args_remove_host: "{{ prop_proxmox_host }}"
