---

- name: "Playbook: Shutdown [{{ args_host }}]"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.proxmox.shutdown
      vars:
        args_shutdown_vmid: "{{ prop_proxmox_vmid }}"
        args_shutdown_host: "{{ prop_proxmox_host }}"
