---

- name: "Playbook: Shutdown VM"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  roles:
    - name: alex.proxmox.status
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
        args_proxmox_host: "{{ prop_proxmox_host }}"
    - name: alex.proxmox.shutdownvm
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
        args_proxmox_host: "{{ prop_proxmox_host }}"
      when: '"RUNNING" in vmstatusresult.stdout'
