---

- name: "Playbook: Start VM"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  roles:
    - name: alex.proxmox.status
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
        args_proxmox_host: "{{ prop_proxmox_host }}"
      failed_when: '"NOTEXIST" in vmstatusresult.stdout'
    - name: alex.proxmox.startvm
      vars:
        args_vmid: "{{ prop_proxmox_vmid }}"
        args_proxmox_host: "{{ prop_proxmox_host }}"
