---

- name: "Playbook: Start [{{ args_host }}]"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.proxmox.start
      vars:
        args_start_vmid: "{{ prop_proxmox_vmid }}"
        args_start_host: "{{ prop_proxmox_host }}"
