---

- name: shutdown vm
  shell: |
    qm shutdown {{ args_vmid }} --skiplock --forceStop
    if [ "$?" -ne "0" ]; then
      echo "FAILED"
      exit 1
    fi
    qm wait {{ args_vmid }}
    if [ "$?" -eq "0" ]; then
      echo "CHANGED"
    else
      echo "FAILED"
    fi
  register: result
  changed_when: '"CHANGED" in result.stdout'
  failed_when: '"FAILED" in result.stdout'
